sudo: false
language: python
python:
- '3.6'
env:
  global:
  - CC_TEST_REPORTER_ID=bfe695a3efcfa8bb6d797c8c9d933ab3d07f50c30d6f0c477133c60b505c6370
addons:
  apt:
    packages:
    - hdf5-tools
install: 
- pip install tox-travis
- ci/get_hdf5_if_needed.sh
- ls -lRa $HDF5_CACHE_DIR
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  >./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script: tox
after_script:
- cd observatory && ../cc-test-reporter format-coverage --input-type coverage.py ../coverage.xml
- "../cc-test-reporter upload-coverage -i coverage/codeclimate.json"
notifications:
  slack:
    secure: WpolD/ZjxSMNebKR6POntT/raDsr4AlB5q5IMRGNzF4DJxyR2H1tyXjJ8Ob3L6Pfn3Hl7b0b2jApezvqclMFpbq9jfwF+DQ7QV45X5ffVZYqh/4nyHSS2n9Uym2asKYoE/25zoC929j9Jw1L/m4E6BI24oOwMicokCMiS0VJjD0M2idL0+KDgt82sktaw3ZAV09o+32T1ZsnnOEI3o9SOiciflzhRQ5OU3zkHbhKWCQ8QQPPKimAgaLg2r0rRMFVrnLdFtxlDc6GrJsFpTJBBb5vtuJWY/MshySSwUEZMVZcAOeX6e6J2PqUO3XUymap2dtsFjAm73KrxRKKRdfHkx+ojqCQXrdbc7JaT25YLv/w4s9U+box9CXxXZkm1A3klZ2mbv0GesfAbBAoUWlnNUxMA1cmwZTcEr+NihBvK3hkbsf5qoyMYu2Tx2l22dwrEJb4YpSjIkCD3TgnE066cWcQG95vK6Axk6veMFutrPMVQzGGEo4YkC0OHg+SCHr+JVk8GfC1ODAfIOJ5TysskfMugrZjrme/NY0Ph3lz9E8T0df0nPLHKIBP+3mE6EO4mbFkuwW0e+evyhzFFx3J8Bfgd+i8rPdR6moL/n1awCiu7h7dDTbd5ZuwDbPvhMX16IdpkTHzI2+ggKSMFVpI1nQjifT/dkEfoDwKlZwWn1g=
