sudo: false
language: python
python:
- '3.6'
env:
  global:
  - CC_TEST_REPORTER_ID=bfe695a3efcfa8bb6d797c8c9d933ab3d07f50c30d6f0c477133c60b505c6370
install: pip install tox-travis
before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  >./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script: tox
after_script:
- cd observatory && ../cc-test-reporter format-coverage --input-type coverage.py ../coverage.xml
- "../cc-test-reporter upload-coverage -i coverage/codeclimate.json"
notifications:
  slack:
    secure: b1hrLLOYZMEU+3ja4eHPwfk+bTgBdLpuXUOQ9lmK91dEnyuN4j+YMDSn4pXHG1q7IqJEKCNN2nkrBnYat9vRtRV3dUeuIWEdW0wPCqBCgTU0lTZ7Y0Grh5wtXKO89PrjPqprFlR+LMc8ImuReNMENugc9LzKT07e6QI31D9jkyifDOjKp+grPj7Mot8eDCsr5f3P9capeM58tLh3DbMVhWf9OxO7kLeJtnTuWsolR5AgtBExJdkTM9/sfoSwOArSOu7etAJSJ7JMzFtuTkhBuXm5hWKnTPWoaAgrDbSeCn+A4LNGKZehxuBLdtx1Mw1fsksinuEP2UevnNpZc1+oPF4zBvZxekim56yjUHZmeL0QZbAAG8ZLCG6nd3MDMc7K1S3AHU6Svt9gmz0pXIuslxPbvef8qKC8QWRZeXGcWC3f/wNPBGvQMo5wtWojFEsd6q4g85FEtNnvmDiz26RtxoxVDAz73vccTzshXrYedr1Ky/zcTGEwOCWsgQxQGZmk8aEcS7Tkl2p0OGksmIJtkyw8VW4ihyfb/P/2yn4iZ7SaRIAiWTEMK3hTqToU0tzGDUCeaFD48kWst3r+X7p+WMTfu2m9CSm6OG+wWnzaj9CmRpugGoetuT4+T3vsZtM9ejlxL5uNnBjGRKsNAXn1pTpKK7GWLtAwXq8IWSoxwkU=
